const io = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('visible') }), {threshold:.14});
document.querySelectorAll('.reveal').forEach(el => io.observe(el));

const stats = document.querySelector('.stats');
let statsStarted = false;
const countObserver = new IntersectionObserver(entries => { if(entries[0].isIntersecting && !statsStarted){ statsStarted = true; document.querySelectorAll('[data-count]').forEach(el => { const target = +el.dataset.count; const start = performance.now(); const tick = now => { const p = Math.min((now-start)/1300,1); el.textContent = Math.floor(target * (1-Math.pow(1-p,3))).toLocaleString('en-IN'); if(p<1) requestAnimationFrame(tick) }; requestAnimationFrame(tick) })}}, {threshold:.4});
if(stats) countObserver.observe(stats);
document.addEventListener('mousemove', e => { const glow=document.querySelector('.cursor-glow'); glow.style.left=e.clientX+'px'; glow.style.top=e.clientY+'px' });
document.querySelectorAll('.nav a[href^="#"], .button[href^="#"], .text-link[href^="#"]').forEach(link => link.addEventListener('click', e => { const target=document.querySelector(link.getAttribute('href')); if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth'})} }));

const rail = document.querySelector('.artist-rail');

const modal = document.querySelector('.booking-modal');
const profileModal = document.querySelector('.profile-modal');
document.querySelectorAll('.calendar-trigger').forEach(button => button.addEventListener('click', () => {
  const card = button.closest('.artist-card'); profileModal.querySelector('.profile-name').textContent = button.dataset.artist;
  profileModal.querySelector('.profile-type').textContent = card.querySelector('.artist-top span').textContent;
  profileModal.querySelector('.profile-rating').textContent = card.querySelector('.rating').textContent.replace('★ ','') + ' / 5';
  profileModal.querySelector('.profile-location').textContent = card.querySelector('.artist-bottom p').textContent;
  profileModal.querySelector('.profile-image').src = card.querySelector('img').src;
  profileModal.classList.add('open'); profileModal.setAttribute('aria-hidden','false');
}));
const closeCalendar = () => { modal.classList.remove('open'); modal.setAttribute('aria-hidden','true') };
modal.querySelector('.modal-close').addEventListener('click', closeCalendar);
modal.querySelector('.modal-backdrop').addEventListener('click', closeCalendar);
modal.querySelectorAll('.calendar-days .available').forEach(day => day.addEventListener('click', () => { modal.querySelectorAll('.calendar-days .selected').forEach(item => item.classList.remove('selected')); day.classList.add('selected') }));
document.querySelector('.rail-next').addEventListener('click', () => rail.scrollBy({left:rail.querySelector('.artist-card').offsetWidth+16,behavior:'smooth'}));
document.querySelector('.rail-prev').addEventListener('click', () => rail.scrollBy({left:-(rail.querySelector('.artist-card').offsetWidth+16),behavior:'smooth'}));
const reviews=[['“A-Hub helped us find an incredible live band for our college fest. The energy was unforgettable.”','Priya Kaushik','Fest Coordinator, Thapar Institute'],['“I booked a DJ who understood our crowd perfectly. Clear availability made it effortless.”','Sanya Arora','Wedding Planner, Chandigarh'],['“My first paid stand-up set came through A-Hub. The profile process feels genuinely professional.”','Kunal Verma','Comedian'],['“We found a live painter for our launch. It transformed the whole evening.”','Rhea Mehta','Brand Manager'],['“The drummer we booked brought our battle of bands to life.”','Aman Sood','College Cultural Secretary'],['“I could see every detail before choosing a choreographer—exactly what organisers need.”','Neha Bansal','College Fest Team'],['“Being clear about the genres I don’t play saved everyone time.”','Kabir Singh','Independent DJ'],['“A brilliant way for artists to present their real work and get discovered.”','Tanya Gill','Independent Singer']];let reviewIndex=0;const reviewText=document.querySelector('.testimonial p'),reviewName=document.querySelector('.quote-person strong'),reviewRole=document.querySelector('.quote-person small'),reviewCount=document.querySelector('.review-count');function showReview(){const r=reviews[reviewIndex];reviewText.textContent=r[0];reviewName.textContent=r[1];reviewRole.textContent=r[2];reviewCount.textContent=String(reviewIndex+1).padStart(2,'0')+' / 08'}showReview();document.querySelector('.review-next').onclick=()=>{reviewIndex=(reviewIndex+1)%reviews.length;showReview()};document.querySelector('.review-prev').onclick=()=>{reviewIndex=(reviewIndex+reviews.length-1)%reviews.length;showReview()};
const closeProfile=()=>profileModal.classList.remove('open');profileModal.querySelector('.profile-close').onclick=closeProfile;profileModal.querySelector('.modal-backdrop').onclick=closeProfile;profileModal.querySelector('.profile-availability').onclick=()=>{closeProfile();modal.classList.add('open')};
const enquiry=document.querySelector('.enquiry-modal');modal.querySelector('.calendar-panel .primary').onclick=()=>{if(!modal.querySelector('.selected'))return;closeCalendar();enquiry.classList.add('open')};enquiry.querySelector('.enquiry-form').onsubmit=e=>{e.preventDefault();e.currentTarget.style.display='none';enquiry.querySelector('.enquiry-success').style.display='block'};const closeEnquiry=()=>enquiry.classList.remove('open');enquiry.querySelector('.enquiry-close').onclick=closeEnquiry;enquiry.querySelector('.modal-backdrop').onclick=closeEnquiry;enquiry.querySelector('.enquiry-ok').onclick=closeEnquiry;
document.querySelectorAll('.artist-card img').forEach((img,i)=>img.addEventListener('error',()=>img.src=`https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=700&q=80&sig=${i}`,{once:true}));
document.querySelector('.partner-list').innerHTML=[['chitkara.edu.in','Chitkara University'],['thapar.edu','Thapar Institute'],['cuchd.in','Chandigarh University'],['pec.ac.in','Punjab Engineering College'],['davchd.ac.in','DAV College']].map(x=>`<article><img src="https://www.google.com/s2/favicons?domain=${x[0]}&sz=128" alt="${x[1]} logo"><span>${x[1]}</span></article>`).join('');
const collegeButton=document.querySelector('.college .button.primary');collegeButton.textContent='Explore college opportunities →';collegeButton.onclick=e=>{e.preventDefault();const p=document.createElement('div');p.className='college-modal open';p.innerHTML='<div class="modal-backdrop"></div><section class="college-panel"><button class="college-close">×</button><span class="kicker">DISCOVER OPEN OPPORTUNITIES</span><h3>Find a stage near you.</h3><p>Choose your region to see events looking for talent.</p><select><option>Chandigarh</option><option>Delhi NCR</option><option>Mumbai</option><option>Bengaluru</option></select><div class="regional-events"><article><b>Chitkara University</b><span>Saturday · Live singers wanted</span></article><article><b>Thapar Fest</b><span>Next weekend · Open showcase for college artists</span></article><article><b>PEC Cultural Night</b><span>18 Aug · DJs, dancers & live bands</span></article></div><button class="button primary college-apply">I want to perform <b>→</b></button></section>';document.body.append(p);p.querySelector('.college-close').onclick=()=>p.remove();p.querySelector('.modal-backdrop').onclick=()=>p.remove();p.querySelector('.college-apply').onclick=()=>{p.querySelector('.college-panel').innerHTML='<h3>You’re on the list.</h3><p>Our team will guide you to relevant opportunities in your region.</p><button class="button primary done">Okay <b>→</b></button>';p.querySelector('.done').onclick=()=>p.remove()}};
collegeButton.onclick=e=>{e.preventDefault();const p=document.createElement('div');p.className='college-modal open';p.innerHTML='<div class="modal-backdrop"></div><section class="college-panel"><button class="college-close">×</button><span class="kicker">STUDENT OPPORTUNITIES</span><h3>Find your next stage.</h3><p>Select a region to discover upcoming fests, open calls, and talent opportunities.</p><select><option>Chandigarh</option><option>Delhi NCR</option><option>Mumbai</option><option>Bengaluru</option></select><div class="regional-events"><article><b>Chitkara University — Saturday</b><span>Live singer registrations open · Certificate provided</span></article><article><b>Thapar Fest — Next weekend</b><span>Open showcase · Build your verified artist portfolio</span></article><article><b>PEC Cultural Night — 18 Aug</b><span>Dancers, DJs & bands · Participation certificate</span></article></div><button class="button primary college-apply">Register for an opportunity <b>→</b></button></section>';document.body.append(p);p.querySelector('.college-close').onclick=()=>p.remove();p.querySelector('.modal-backdrop').onclick=()=>p.remove();p.querySelector('.college-apply').onclick=()=>{p.querySelector('.college-panel').innerHTML='<h3>Registration started.</h3><p>Complete your artist profile to register, receive participation certificates, and add this experience to your A‑Hub portfolio.</p><button class="button primary done">Okay <b>→</b></button>';p.querySelector('.done').onclick=()=>p.remove()}};
collegeButton.onclick=()=>location.href='college-opportunities.html';
document.addEventListener('DOMContentLoaded',()=>{const register=document.querySelector('.artist-journey .button');if(register)register.onclick=e=>{e.preventDefault();location.href='creator-registration.html'};const creator=JSON.parse(localStorage.getItem('ahubCreator')||'null');if(creator){const card=document.querySelector('.artist-rail .artist-card');if(card){card.querySelector('h3').textContent=creator.name;card.querySelector('.artist-top span').textContent=creator.category.toUpperCase();card.querySelector('.artist-bottom p').textContent=creator.city;card.onclick=()=>location.href='creator-profile.html'}}});

document.addEventListener('DOMContentLoaded',()=>{const creator=JSON.parse(localStorage.getItem('ahubCreator')||'null'),image=localStorage.getItem('ahubCreatorImage');if(creator){const card=document.querySelector('.artist-rail .artist-card');if(card&&image)card.querySelector('img').src=image}});
